[default-hotkey]
RCtrl & 1 = showMsg
RCtrl & 2 = showMsg2
RCtrl & 3 = firework
RCtrl & 4 = test__SleepTimer
RCtrl & = = showMsg3
RAlt & 1 = 
RAlt & 2 = showMsg4
;----------
[Window]
Pos=x-929 y846
AlwaysOnTop=ON
;----------
[Hotkey]
RCtrl & 1 = showMsg
RCtrl & 2 = fish
RCtrl & 3 = firework
RCtrl & 4 = test__SleepTimer
RCtrl & = = showMsg
RALT & 1 = showMsg
RALT & 2 = showMsg2
