[default-hotkey]
RCtrl & 1 = test__SleepTimer
RAlt & 1 = test__MsgBox
;----------
[System]
LastActionTime=20260502095654
;----------
[Window]
Pos=x-379 y1171
AlwaysOnTop=ON
;----------
[Hotkey]
RCtrl & 1 = test__SleepTimer
RAlt & 1 = DPS_Sword_Lv5
